///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Images {
  Images._();

  static const String fontsSatoshiBlack = 'assets/fonts/Satoshi-Black.ttf';
  static const String fontsSatoshiBold = 'assets/fonts/Satoshi-Bold.ttf';
  static const String fontsSatoshiLight = 'assets/fonts/Satoshi-Light.ttf';
  static const String fontsSatoshiMedium = 'assets/fonts/Satoshi-Medium.ttf';
  static const String fontsSatoshiRegular = 'assets/fonts/Satoshi-Regular.ttf';
  static const String imagesAuthHome = 'assets/images/auth_home.png';
  static const String imagesBottomPattern = 'assets/images/bottom_pattern.png';
  static const String imagesOnboarding1 = 'assets/images/onboarding1.png';
  static const String imagesThemeBackground =
      'assets/images/theme_background.png';
  static const String imagesTopPattern = 'assets/images/top_pattern.png';
  static const String vectorsGoogle = 'assets/vectors/google.svg';
  static const String vectorsMoon = 'assets/vectors/moon.svg';
  static const String vectorsSpotifyLogo = 'assets/vectors/spotify_logo.svg';
  static const String vectorsSun = 'assets/vectors/sun.svg';
}
